name: numd
description: A rudimentary numerical computing library for Dart, inspired by NumPy
version: 1.0.0
repository: https://github.com/RishiAhuja/numd.git

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

license: MIT
